dist: xenial
language: minimal
services:
  - docker
env:
  global:
    - VERSION=4.6.0
    - COMMIT=449e06c
    - BRANCH=master
    - URL=http://127.0.0.1:8080/exist/rest/db

jobs:
   include:
     - stage: build docker images
       name: via VERSION tag
       script: docker build --tag existdb/existdb:${VERSION} --build-arg "VERSION=${VERSION}" .
     - script: docker build --tag existdb/existdb:${COMMIT} --build-arg "BRANCH=${COMMIT}" .
       name: via BRANCH commit
     - script: docker build --tag existdb/existdb:${BRANCH} --build-arg "BRANCH=${BRANCH}" .
       name: via BRANCH name
     - stage: test
       script: docker ps


notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX

# TODO maybe
# a # listing files in config dir
#  # CHECK! with the exist containers provided config dir,
#  # a user should be able to list configuration files
#  # that will enable user to alter eXist start up options.
#  set -eo pipefail
#  cat <<EOF | curl -s -H 'Content-Type: text/xml' -u 'admin:nimda' --data-binary @- "$URL"
#  <query xmlns='http://exist.sourceforge.net/NS/exist' start='1' max='99' wrap='no'>
#  <text><![CDATA[
#  xquery version '3.1';
#  let $eXistHome := system:get-exist-home()
#  let $configDir := concat($eXistHome, '/config')
#  let $fileList := file:list( configDir )
#  return
#   $fileList
#  ]]></text>
#  </query>
#  EOF
