sudo: required
dist: trusty
language: c
services:
  - docker

before_install:
  - docker --version
  - docker-compose --version
  - docker build -t existdb/existdb .
  - docker-compose up -d

before_script:
  - sleep 35
script:
  - docker exec exist java -version
  - docker logs exist
  - docker ps -a
