sudo: false
dist: trusty
language: c
services:
  - docker

jobs:
   include:
     - stage: build image
       env: VERSION=4.3.1
       install: skip
       script:
       - docker build --tag existdb/existdb:${VERSION} --build-arg "VERSION=${VERSION}" .
       - docker-compose up -d
       - docker ps -a
   include:
     - stage: build image
       env: BRANCH=master
       install: skip
       script:
       - docker build --tag existdb/existdb:${BRANCH} --build-arg "BRANCH=${BRANCH}" .
