dist: xenial
language: minimal

env:
  global:
    - VERSION=4.6.0
    - COMMIT=449e06c
    - BRANCH=develop
    - URL=http://127.0.0.1:8080/exist/rest/db

services:
  - docker

jobs:
   include:
     - stage: build docker images
       name: via VERSION tag
       script: docker build --tag existdb/exist-ci-build:${VERSION} --build-arg "VERSION=${VERSION}" .
     - script: docker build --tag existdb/exist-ci-build:${COMMIT} --build-arg "BRANCH=${COMMIT}" .
       name: via BRANCH commit
     - script:
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker build --tag existdb/exist-ci-build:${BRANCH} --build-arg "BRANCH=${BRANCH}" .
       - docker push existdb/exist-ci-build
       name: via BRANCH name
     - stage: test
       script:
         - docker run -dit -p 8080:8080 --rm existdb/exist-ci-build:${BRANCH}
         - docker ps


notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
