dist: xenial
language: minimal

env:
  global:
    - VERSION=4.6.0
    - COMMIT=449e06c
    - BRANCH=develop

services:
  - docker

jobs:
   include:
     - stage: build docker images
       name: via VERSION tag
       script: docker build --tag existdb/exist-ci-build:${VERSION} --build-arg "VERSION=${VERSION}" .
     - script: docker build --tag existdb/exist-ci-build:${COMMIT} --build-arg "BRANCH=${COMMIT}" .
       name: via BRANCH commit
     - script:
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker build --tag existdb/exist-ci-build:latest --build-arg "BRANCH=${BRANCH}" .
       - docker push existdb/exist-ci-build
       name: via BRANCH name
     - stage: test
       before_install: docker run -dit -p 8080:8080 --rm --name exist existdb/exist-ci-build:latest
       install:
         - sudo add-apt-repository ppa:duggan/bats --yes
         - sudo apt-get update -qq
         - sudo apt-get install -qq bats
         - sleep 20
       script: bats --tap test/*.bats


notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
