sudo: true
dist: trusty
language: c
services:
  - docker

jobs:
   include:
     - stage: build image
       env: VERSION=4.3.1
       install: skip
       script:
       - docker build --tag existdb/existdb:${VERSION} --build-arg "VERSION=${VERSION}" .

