version: '3.6'
services:
  exist:
    image: $DOCKER_IMAGE:$DOCKER_TAG
    container_name: exist
    ports:
        - 8080:8080
        - 8443:8443
    networks:
      - www
    volumes:
      - type: volume
        source: data
        target: ${EXIST_HOME}/${EXIST_DATA_DIR}
      - type: volume
        source: config
        target: ${EXIST_HOME}/${EXIST_CONFIG_DIR}

volumes:
  data:
    driver: local
    name: exist-data
  config:
    driver: local
    name: exist-config

networks:
  www:
    name: www
    driver: bridge
