#!/bin/bash
set -xe

# see https://docs.docker.com/docker-cloud/builds/advanced/

. ./hooks/env

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
             --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg VERSION="$REL_VER" \
             -t "$IMAGE_NAME" .
