#!/bin/bash
set -xe

# see https://docs.docker.com/docker-cloud/builds/advanced/

. ./hooks/env

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}


# Tag and push image for each additional tag
for tag in {$REL_VER,release}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
