name: Test
on: [push, pull_request]
jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build --build-arg BRANCH=develop-4.x.x --tag existdb/existdb-ci-build:4.x.x-SNAPSHOT .
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker Image
        run: docker push existdb/existdb-ci-build:4.x.x-SNAPSHOT
  test:
    name: Test Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Docker Container
        run: docker run -dit -p 8080:8080 --rm --name exist existdb/existdb-ci-build:4.x.x-SNAPSHOT
      - uses: actions/checkout@v2
      - name: Install Bats
        run: sudo apt-get -y install bats
      - name: Wait for eXist-db to Start
        run: timeout 90 sh -c 'until nc -z $0 $1; do sleep 3; done' localhost 8080
      - name: Run Bats Tests
        run: bats --tap test/*.bats
      - name: Stop Docker Container
        if: always()
        run: docker stop exist
